import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:altr_stream_admin/core/api/api_client.dart';
import 'package:altr_stream_admin/core/api/models.dart';
import 'package:altr_stream_admin/core/theme/app_theme.dart';
import 'package:altr_stream_admin/features/docs/screens/api_docs_screen.dart';
import 'package:altr_stream_admin/features/docs/services/openapi_parser.dart';
import 'package:altr_stream_admin/features/docs/widgets/api_console_header.dart';
import 'package:altr_stream_admin/features/docs/widgets/api_curl_generator.dart';
import 'package:altr_stream_admin/features/docs/widgets/api_endpoint_documentation.dart';
import 'package:altr_stream_admin/features/docs/widgets/api_endpoint_sidebar.dart';
import 'package:altr_stream_admin/features/docs/widgets/api_parameter_card.dart';
import 'package:altr_stream_admin/features/docs/widgets/api_request_body_card.dart';
import 'package:altr_stream_admin/features/docs/widgets/api_try_it_out_panel.dart';

// Sample OpenAPI 3.1 Spec for testing
const Map<String, dynamic> sampleOpenApiSpec = {
  "openapi": "3.1.0",
  "info": {
    "title": "Altr Stream Query Engine",
    "version": "0.8.0",
    "description": "Cross-database query engine and registry API",
  },
  "paths": {
    "/api/v1/execute": {
      "post": {
        "tags": ["Execution"],
        "summary": "Execute AltrQL Query",
        "description":
            "Execute cross-database query against registered sources",
        "operationId": "execute_query_api_v1_execute_post",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {"\$ref": "#/components/schemas/AltrQLExecuteRequest"},
            },
          },
        },
        "responses": {
          "200": {
            "description": "Query execution results",
            "content": {
              "application/json": {
                "schema": {
                  "\$ref": "#/components/schemas/AltrQLExecuteResponse",
                },
              },
            },
          },
          "422": {"description": "Validation Error"},
        },
      },
    },
    "/api/v1/sources": {
      "get": {
        "tags": ["Data Sources"],
        "summary": "List Data Sources",
        "description": "Retrieve all registered physical data sources",
        "operationId": "list_sources_api_v1_sources_get",
        "responses": {
          "200": {"description": "List of sources"},
        },
      },
      "post": {
        "tags": ["Data Sources"],
        "summary": "Create Data Source",
        "description": "Register a new physical database connection",
        "operationId": "create_source_api_v1_sources_post",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {"\$ref": "#/components/schemas/SourceCreateRequest"},
            },
          },
        },
        "responses": {
          "201": {"description": "Source created successfully"},
        },
      },
    },
    "/api/v1/sources/{source_id}": {
      "get": {
        "tags": ["Data Sources"],
        "summary": "Get Source Details",
        "description": "Retrieve connection details and metadata for a source",
        "parameters": [
          {
            "name": "source_id",
            "in": "path",
            "required": true,
            "description": "UUID of the physical source",
            "schema": {"type": "string", "format": "uuid"},
          },
        ],
        "responses": {
          "200": {"description": "Source details"},
          "404": {"description": "Source not found"},
        },
      },
      "delete": {
        "tags": ["Data Sources"],
        "summary": "Delete Data Source",
        "description": "Remove a data source connection",
        "parameters": [
          {
            "name": "source_id",
            "in": "path",
            "required": true,
            "description": "UUID of the physical source",
            "schema": {"type": "string", "format": "uuid"},
          },
        ],
        "responses": {
          "200": {"description": "Source deleted"},
        },
      },
    },
    "/api/v1/registry/models/{model_id}/align/suggestions": {
      "post": {
        "tags": ["Registry"],
        "summary": "Ingest Align Suggestions",
        "description":
            "Ingest schema alignment proposals generated by Altr Align",
        "parameters": [
          {
            "name": "model_id",
            "in": "path",
            "required": true,
            "description": "UUID of the target canonical logical model",
            "schema": {"type": "string", "format": "uuid"},
          },
          {
            "name": "confidence_threshold",
            "in": "query",
            "required": false,
            "description": "Minimum confidence threshold for ingestion",
            "schema": {"type": "number", "default": 0.8},
          },
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "\$ref": "#/components/schemas/AlignSuggestionIngestRequest",
              },
            },
          },
        },
        "responses": {
          "201": {"description": "Alignment proposals ingested successfully"},
        },
      },
    },
    "/api/v1/registry/models/{model_id}/resolve/{entity_name}": {
      "get": {
        "tags": ["Registry"],
        "summary": "Resolve Logical Entity",
        "description":
            "Discover physical table and column mappings for an entity",
        "parameters": [
          {
            "name": "model_id",
            "in": "path",
            "required": true,
            "description": "Canonical Logical Model ID",
            "schema": {"type": "string", "format": "uuid"},
          },
          {
            "name": "entity_name",
            "in": "path",
            "required": true,
            "description": "Logical entity name to resolve",
            "schema": {"type": "string"},
          },
        ],
        "responses": {
          "200": {"description": "Resolution mapping details"},
        },
      },
    },
    "/api/v1/altrql/bind": {
      "post": {
        "tags": ["AltrQL"],
        "summary": "Bind AltrQL Query",
        "description":
            "Bind a parsed AltrQL query against registered source schema",
        "operationId": "bind_altrql_query_api_v1_altrql_bind_post",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {"\$ref": "#/components/schemas/AltrQLBindRequest"},
            },
          },
        },
        "responses": {
          "200": {"description": "Successful binding response"},
          "422": {"description": "Validation Error"},
        },
      },
    },
    "/api/v1/health": {
      "get": {
        "tags": ["System"],
        "summary": "System Health",
        "description": "Query engine runtime health",
        "responses": {
          "200": {"description": "Node status"},
        },
      },
    },
  },
  "components": {
    "schemas": {
      "AltrQLBindRequest": {
        "title": "AltrQLBindRequest",
        "type": "object",
        "required": ["query", "source_id"],
        "properties": {
          "query": {
            "title": "Query",
            "type": "string",
            "example": "SELECT * FROM users",
          },
          "source_id": {"title": "Source Id", "type": "string"},
          "mapping_id": {
            "title": "Mapping Id",
            "anyOf": [
              {"type": "string"},
              {"type": "null"},
            ],
            "default": null,
          },
          "logical_model_id": {
            "title": "Logical Model Id",
            "anyOf": [
              {"type": "string"},
              {"type": "null"},
            ],
            "default": null,
          },
        },
      },
      "AltrQLExecuteRequest": {
        "title": "AltrQLExecuteRequest",
        "type": "object",
        "required": ["query"],
        "properties": {
          "query": {
            "title": "AltrQL Query",
            "type": "string",
            "example": "SELECT u.id, u.name FROM users u",
          },
          "limit": {"title": "Limit", "type": "integer", "default": 100},
        },
      },
      "AltrQLExecuteResponse": {
        "title": "AltrQLExecuteResponse",
        "type": "object",
        "properties": {
          "success": {"type": "boolean"},
          "columns": {
            "type": "array",
            "items": {"type": "string"},
          },
          "rows": {
            "type": "array",
            "items": {"type": "object"},
          },
          "execution_time_ms": {"type": "number"},
        },
      },
      "SourceCreateRequest": {
        "title": "SourceCreateRequest",
        "type": "object",
        "required": ["name", "type"],
        "properties": {
          "name": {"type": "string", "example": "Production-MongoDB"},
          "type": {
            "type": "string",
            "enum": ["POSTGRESQL", "MYSQL", "SQLITE", "MONGODB"],
          },
          "host": {"type": "string", "default": "localhost"},
          "port": {"type": "integer", "default": 27017},
        },
      },
      "AlignSuggestionIngestRequest": {
        "title": "AlignSuggestionIngestRequest",
        "type": "object",
        "required": ["source_id", "proposals"],
        "properties": {
          "source_id": {"type": "string", "format": "uuid"},
          "proposals": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "logical_entity": {"type": "string"},
                "physical_entity": {"type": "string"},
                "confidence": {"type": "number", "default": 0.95},
              },
            },
          },
        },
      },
    },
  },
};

class MockApiExplorerClient extends ApiClient {
  final Map<String, dynamic>? specToReturn;
  final bool shouldFailSpec;
  final ApiExecutionResult? executionResultToReturn;
  final List<LogicalModelModel>? modelsToReturn;
  final List<SourceModel>? sourcesToReturn;
  final List<SourceMappingModel>? mappingsToReturn;
  final SourceSchemaModel? schemaToReturn;

  String? lastExecutedMethod;
  String? lastExecutedPath;
  Map<String, String>? lastExecutedPathParams;
  Map<String, dynamic>? lastExecutedQueryParams;
  dynamic lastExecutedBody;

  MockApiExplorerClient({
    this.specToReturn,
    this.shouldFailSpec = false,
    this.executionResultToReturn,
    this.modelsToReturn,
    this.sourcesToReturn,
    this.mappingsToReturn,
    this.schemaToReturn,
  });

  @override
  Future<Map<String, dynamic>> getOpenApiSpec() async {
    if (shouldFailSpec) {
      throw ApiException(
        statusCode: 500,
        message: 'Failed to connect to OpenAPI endpoint',
      );
    }
    return specToReturn ?? sampleOpenApiSpec;
  }

  @override
  Future<List<SourceModel>> listSources({bool probe = false}) async {
    return sourcesToReturn ??
        [
          SourceModel(
            id: '9f8b7a6c-5d4e-3f2a-1b0c-9d8e7f6a5b4c',
            name: 'Production-MongoDB',
            type: 'MONGODB',
            databaseName: 'altr_test_db',
            status: 'ACTIVE',
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          ),
        ];
  }

  @override
  Future<SourceSchemaModel?> getLatestSchema(String sourceId) async {
    return schemaToReturn ??
        SourceSchemaModel(
          sourceId: sourceId,
          sourceName: 'Production-MongoDB',
          version: '1.0.0',
          discoveredAt: DateTime.now(),
          entities: [
            EntitySchemaModel(
              name: 'parity_users',
              namespace: 'altr_test_db',
              entityType: 'COLLECTION',
              fields: [
                FieldSchemaModel(
                  name: '_id',
                  dataType: 'STRING',
                  nativeDataType: 'ObjectId',
                  nullable: false,
                  isPrimaryKey: true,
                  position: 1,
                ),
                FieldSchemaModel(
                  name: 'name',
                  dataType: 'STRING',
                  nativeDataType: 'String',
                  nullable: true,
                  isPrimaryKey: false,
                  position: 2,
                ),
              ],
              primaryKey: ['_id'],
              constraints: [],
            ),
          ],
          metadata: {},
        );
  }

  @override
  Future<List<SourceMappingModel>> listSourceMappings({
    String? modelId,
    String? sourceId,
    String? status,
  }) async {
    return mappingsToReturn ??
        [
          SourceMappingModel(
            id: '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
            logicalModelId: '5b1ee481-68dd-4c4d-ba34-6c884b166b35',
            sourceId: '9f8b7a6c-5d4e-3f2a-1b0c-9d8e7f6a5b4c',
            version: '1.0.0',
            status: 'ACTIVE',
            provenance: 'USER',
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          ),
        ];
  }

  @override
  Future<List<LogicalModelModel>> listLogicalModels() async {
    return modelsToReturn ??
        [
          LogicalModelModel(
            id: '5b1ee481-68dd-4c4d-ba34-6c884b166b35',
            name: 'ParityUsersModel',
            description: 'Canonical logical model for users',
            version: '1.0.0',
            entities: [
              LogicalEntityModel(
                id: 'entity-users-1',
                logicalModelId: '5b1ee481-68dd-4c4d-ba34-6c884b166b35',
                name: 'users',
                description: 'User accounts',
                fields: [
                  LogicalFieldModel(
                    id: 'field-name-1',
                    logicalEntityId: 'entity-users-1',
                    name: 'name',
                    dataType: 'STRING',
                    nullable: true,
                    isPrimaryKey: false,
                    createdAt: DateTime.now(),
                    updatedAt: DateTime.now(),
                  ),
                ],
                createdAt: DateTime.now(),
                updatedAt: DateTime.now(),
              ),
            ],
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          ),
        ];
  }

  @override
  Future<ApiExecutionResult> executeRawRequest({
    required String method,
    required String path,
    Map<String, String>? pathParams,
    Map<String, dynamic>? queryParams,
    dynamic body,
    Map<String, String>? customHeaders,
  }) async {
    lastExecutedMethod = method;
    lastExecutedPath = path;
    lastExecutedPathParams = pathParams;
    lastExecutedQueryParams = queryParams;
    lastExecutedBody = body;

    return executionResultToReturn ??
        ApiExecutionResult(
          statusCode: 200,
          statusText: '200 OK',
          duration: const Duration(milliseconds: 42),
          requestMethod: method.toUpperCase(),
          requestUrl: 'http://localhost:8000$path',
          requestHeaders: {'Content-Type': 'application/json'},
          requestBody: body is String ? body : body?.toString(),
          responseHeaders: {'content-type': 'application/json'},
          responseBody: {
            'status': 'success',
            'data': {'count': 1, 'items': []},
          },
          errorMessage: null,
          isSuccess: true,
        );
  }
}

void main() {
  group('OpenAPI Parser & Models Unit Tests', () {
    test('OpenApiParser parses endpoints, methods, and tags dynamically', () {
      final parsed = OpenApiParser.parse(sampleOpenApiSpec);

      expect(parsed.title, 'Altr Stream Query Engine');
      expect(parsed.version, '0.8.0');
      expect(parsed.endpoints.length, 9);

      // Discovered methods: GET, POST, DELETE
      expect(parsed.discoveredMethods.contains('GET'), isTrue);
      expect(parsed.discoveredMethods.contains('POST'), isTrue);
      expect(parsed.discoveredMethods.contains('DELETE'), isTrue);

      // Discovered tags
      expect(parsed.discoveredTags.contains('Execution'), isTrue);
      expect(parsed.discoveredTags.contains('Data Sources'), isTrue);
      expect(parsed.discoveredTags.contains('Registry'), isTrue);
      expect(parsed.discoveredTags.contains('System'), isTrue);
    });

    test(
      'OpenApiParser generates intelligent request body samples from schema with refs',
      () {
        final parsed = OpenApiParser.parse(sampleOpenApiSpec);

        final executeEp = parsed.endpoints.firstWhere(
          (e) => e.path == '/api/v1/execute' && e.method == 'POST',
        );
        expect(executeEp.hasRequestBody, isTrue);
        expect(executeEp.requestBody, isNotNull);
        expect(executeEp.requestBody!.sampleJson.contains('"query"'), isTrue);
        expect(executeEp.requestBody!.sampleJson.contains('"limit"'), isTrue);

        final alignEp = parsed.endpoints.firstWhere(
          (e) => e.path.contains('/align/suggestions'),
        );
        expect(alignEp.hasRequestBody, isTrue);
        expect(alignEp.requestBody!.sampleJson.contains('"source_id"'), isTrue);
        expect(alignEp.requestBody!.sampleJson.contains('"proposals"'), isTrue);
      },
    );

    test(
      'ApiEndpoint matchesSearch performs case-insensitive search across attributes',
      () {
        final parsed = OpenApiParser.parse(sampleOpenApiSpec);
        final alignEp = parsed.endpoints.firstWhere(
          (e) => e.path.contains('/align/suggestions'),
        );

        // Path match
        expect(alignEp.matchesSearch('align'), isTrue);
        expect(alignEp.matchesSearch('ALIGN'), isTrue);
        expect(alignEp.matchesSearch('suggestions'), isTrue);

        // Method match
        expect(alignEp.matchesSearch('post'), isTrue);

        // Tag match
        expect(alignEp.matchesSearch('registry'), isTrue);

        // Summary match
        expect(alignEp.matchesSearch('Ingest'), isTrue);

        // Parameter match
        expect(alignEp.matchesSearch('confidence_threshold'), isTrue);
        expect(alignEp.matchesSearch('model_id'), isTrue);

        // Non-matching
        expect(alignEp.matchesSearch('nonexistent_keyword_xyz'), isFalse);
      },
    );

    test(
      'ApiCurlGenerator generates multi-line curl string with headers and body',
      () {
        final curl = ApiCurlGenerator.generate(
          method: 'POST',
          url: 'http://localhost:8000/api/v1/execute',
          headers: {'X-Custom': 'val'},
          body: '{"query": "SELECT 1"}',
        );

        expect(
          curl.contains('curl -X POST "http://localhost:8000/api/v1/execute"'),
          isTrue,
        );
        expect(curl.contains('-H "Content-Type: application/json"'), isTrue);
        expect(curl.contains('-H "X-Custom: val"'), isTrue);
        expect(curl.contains("-d '{\"query\": \"SELECT 1\"}'"), isTrue);
      },
    );
  });

  group('Flutter Native API Explorer Widget Tests', () {
    testWidgets(
      'ApiDocsScreen renders loading state and loads OpenAPI endpoints',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );

        // Initially shows title and loading indicator
        expect(find.text('API Explorer'), findsOneWidget);

        await tester.pumpAndSettle();

        // Endpoints loaded
        expect(find.text('9 endpoints'), findsOneWidget);
        expect(find.text('/api/v1/execute'), findsWidgets);
        expect(find.text('/api/v1/sources'), findsWidgets);
        expect(find.text('/api/v1/health'), findsWidgets);
      },
    );

    testWidgets(
      'ApiDocsScreen renders error state with retry on OpenAPI load failure',
      (WidgetTester tester) async {
        final failingClient = MockApiExplorerClient(shouldFailSpec: true);

        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: failingClient)),
          ),
        );

        await tester.pumpAndSettle();

        expect(
          find.text('Failed to Load OpenAPI Specification'),
          findsOneWidget,
        );
        expect(find.text('Retry Loading OpenAPI'), findsOneWidget);
      },
    );

    testWidgets(
      'Search APIs filter updates in real time by path, summary, and parameters',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Search 'align'
        await tester.enterText(
          find.byKey(const Key('api_search_input')),
          'align',
        );
        await tester.pumpAndSettle();

        expect(find.text('1 of 9 endpoints'), findsOneWidget);
        expect(
          find.text('/api/v1/registry/models/{model_id}/align/suggestions'),
          findsWidgets,
        );
        expect(find.text('/api/v1/execute'), findsNothing);

        // Clear search
        await tester.tap(find.byTooltip('Clear search'));
        await tester.pumpAndSettle();
        expect(find.text('9 endpoints'), findsOneWidget);

        // Search parameter name 'confidence_threshold'
        await tester.enterText(
          find.byKey(const Key('api_search_input')),
          'confidence_threshold',
        );
        await tester.pumpAndSettle();
        expect(find.text('1 of 9 endpoints'), findsOneWidget);
        expect(
          find.text('/api/v1/registry/models/{model_id}/align/suggestions'),
          findsWidgets,
        );
      },
    );

    testWidgets(
      'Dynamic Method and Tag filters filter endpoint list correctly',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Method Dropdown: Select DELETE
        await tester.tap(find.byKey(const Key('api_method_filter_dropdown')));
        await tester.pumpAndSettle();
        await tester.tap(find.text('DELETE').last);
        await tester.pumpAndSettle();

        expect(find.text('1 of 9 endpoints'), findsOneWidget);
        expect(find.text('/api/v1/sources/{source_id}'), findsWidgets);

        // Reset filters
        await tester.tap(find.text('Reset Filters'));
        await tester.pumpAndSettle();
        expect(find.text('9 endpoints'), findsOneWidget);

        // Tag Dropdown: Select Execution
        await tester.tap(find.byKey(const Key('api_tag_filter_dropdown')));
        await tester.pumpAndSettle();
        await tester.tap(find.text('Execution').last);
        await tester.pumpAndSettle();

        expect(find.text('1 of 9 endpoints'), findsOneWidget);
        expect(find.text('/api/v1/execute'), findsWidgets);
      },
    );

    testWidgets(
      'Selecting an endpoint displays details, parameters, and request body',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Tap on POST /api/v1/registry/models/{model_id}/align/suggestions
        final alignFinder = find.byKey(
          const Key(
            'api_endpoint_POST_/api/v1/registry/models/{model_id}/align/suggestions',
          ),
        );
        expect(alignFinder, findsOneWidget);
        await tester.tap(alignFinder);
        await tester.pumpAndSettle();

        // Verify Detail Panel
        expect(find.text('Ingest Align Suggestions'), findsWidgets);
        expect(find.text('PATH PARAMETERS'), findsOneWidget);
        expect(find.text('model_id'), findsWidgets);
        expect(find.text('QUERY PARAMETERS'), findsOneWidget);
        expect(find.text('confidence_threshold'), findsWidgets);
        expect(find.text('Request Body'), findsOneWidget);
        expect(find.text('Execute Request'), findsOneWidget);
      },
    );

    testWidgets(
      'Request body Format JSON and Reset Template work as expected',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Tap on POST /api/v1/execute
        final execFinder = find.byKey(
          const Key('api_endpoint_POST_/api/v1/execute'),
        );
        await tester.tap(execFinder);
        await tester.pumpAndSettle();

        // Enter minified JSON in body editor
        final editorFinder = find.byKey(const Key('api_request_body_editor'));
        await tester.enterText(
          editorFinder,
          '{"query":"SELECT u.id FROM users u","limit":10}',
        );
        await tester.pumpAndSettle();

        // Format JSON
        await tester.tap(find.byKey(const Key('api_format_json_button')));
        await tester.pumpAndSettle();

        final TextField editorWidget = tester.widget(editorFinder);
        expect(
          editorWidget.controller!.text.contains(
            '  "query": "SELECT u.id FROM users u"',
          ),
          isTrue,
        );

        // Reset Template
        await tester.tap(find.byKey(const Key('api_reset_template_button')));
        await tester.pumpAndSettle();
        expect(editorWidget.controller!.text.contains('"query"'), isTrue);
      },
    );

    testWidgets(
      'Executing request displays live response with status 200 OK and latency',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient(
          executionResultToReturn: ApiExecutionResult(
            statusCode: 200,
            statusText: '200 OK',
            duration: const Duration(milliseconds: 35),
            requestMethod: 'POST',
            requestUrl: 'http://localhost:8000/api/v1/execute',
            requestHeaders: {'Content-Type': 'application/json'},
            requestBody: '{"query": "SELECT 1"}',
            responseHeaders: {'content-type': 'application/json'},
            responseBody: {
              'result': 'success',
              'rows': [1, 2, 3],
            },
            isSuccess: true,
          ),
        );

        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Select /api/v1/execute
        await tester.tap(
          find.byKey(const Key('api_endpoint_POST_/api/v1/execute')),
        );
        await tester.pumpAndSettle();

        // Execute request
        await tester.tap(find.byKey(const Key('api_execute_button')));
        await tester.pumpAndSettle();

        // Verify response viewer renders
        expect(find.text('Execution Response'), findsOneWidget);
        expect(find.text('200 OK'), findsOneWidget);
        expect(find.text('35ms'), findsOneWidget);
        expect(find.textContaining('"result": "success"'), findsOneWidget);
        expect(mockClient.lastExecutedMethod, 'POST');
        expect(mockClient.lastExecutedPath, '/api/v1/execute');
      },
    );

    testWidgets(
      'Executing request with backend error displays real error message and status code',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient(
          executionResultToReturn: ApiExecutionResult(
            statusCode: 404,
            statusText: '404 Not Found',
            duration: const Duration(milliseconds: 18),
            requestMethod: 'GET',
            requestUrl: 'http://localhost:8000/api/v1/sources/nonexistent-id',
            requestHeaders: {},
            responseHeaders: {},
            responseBody: {
              'detail': "Source with id 'nonexistent-id' was not found.",
            },
            errorMessage: "Source with id 'nonexistent-id' was not found.",
            isSuccess: false,
          ),
        );

        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Select GET /api/v1/sources/{source_id}
        await tester.tap(
          find.byKey(const Key('api_endpoint_GET_/api/v1/sources/{source_id}')),
        );
        await tester.pumpAndSettle();

        // Enter path param
        await tester.enterText(
          find.byKey(const Key('api_param_input_source_id')),
          'nonexistent-id',
        );
        await tester.pumpAndSettle();

        // Execute
        await tester.tap(find.byKey(const Key('api_execute_button')));
        await tester.pumpAndSettle();

        // Verify 404 Not Found and backend error message
        expect(find.text('404 Not Found'), findsOneWidget);
        expect(
          find.text("Source with id 'nonexistent-id' was not found."),
          findsWidgets,
        );
      },
    );

    testWidgets(
      'Altr Stream Contextual Helper populates model_id from dropdown',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Select endpoint with model_id
        await tester.tap(
          find.byKey(
            const Key(
              'api_endpoint_POST_/api/v1/registry/models/{model_id}/align/suggestions',
            ),
          ),
        );
        await tester.pumpAndSettle();

        // Verify Logical Model dropdown helper is visible
        expect(
          find.byKey(const Key('api_param_model_selector')),
          findsOneWidget,
        );
        await tester.tap(find.byKey(const Key('api_param_model_selector')));
        await tester.pumpAndSettle();

        // Select ParityUsersModel
        await tester.tap(find.textContaining('ParityUsersModel').last);
        await tester.pumpAndSettle();

        // Parameter input text field is populated with UUID
        final paramInput = tester.widget<TextField>(
          find.byKey(const Key('api_param_input_model_id')),
        );
        expect(
          paramInput.controller!.text,
          '5b1ee481-68dd-4c4d-ba34-6c884b166b35',
        );
      },
    );

    testWidgets(
      'Swagger Fallback and cURL quick reference cards are rendered',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(
              body: SingleChildScrollView(
                child: ApiDocsScreen(apiClient: mockClient),
              ),
            ),
          ),
        );
        await tester.pumpAndSettle();

        expect(find.text('OpenAPI / Swagger Documentation'), findsOneWidget);
        expect(find.text('Launch Swagger UI (/docs)'), findsOneWidget);
        expect(find.text('Open ReDoc (/redoc)'), findsOneWidget);
        expect(find.text('OpenAPI JSON (/openapi.json)'), findsOneWidget);
        expect(find.text('Quick cURL Request Reference'), findsOneWidget);
      },
    );

    // --- REGRESSION TESTS: SCHEMA GENERATION & ALTRQL EXECUTION ---

    test('1. OpenAPI string schema generates string value "", not {}', () {
      final spec = {
        "openapi": "3.1.0",
        "info": {"title": "Test", "version": "1.0.0"},
        "paths": {
          "/test": {
            "post": {
              "requestBody": {
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "name": {"type": "string"},
                        "nullable_field": {
                          "anyOf": [
                            {"type": "string"},
                            {"type": "null"},
                          ],
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      };

      final data = OpenApiParser.parse(spec);
      final sample = data.endpoints.first.requestBody!.sampleJson;
      expect(sample.contains('"name": ""'), isTrue);
      expect(sample.contains('"nullable_field": ""'), isTrue);
      expect(sample.contains('"name": {}'), isFalse);
      expect(sample.contains('"nullable_field": {}'), isFalse);
    });

    test('2. Integer schema generates integer 0 and number generates 0', () {
      final spec = {
        "openapi": "3.1.0",
        "info": {"title": "Test", "version": "1.0.0"},
        "paths": {
          "/test": {
            "post": {
              "requestBody": {
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "count": {"type": "integer"},
                        "ratio": {"type": "number"},
                      },
                    },
                  },
                },
              },
            },
          },
        },
      };

      final data = OpenApiParser.parse(spec);
      final sample = data.endpoints.first.requestBody!.sampleJson;
      expect(sample.contains('"count": 0'), isTrue);
      expect(sample.contains('"ratio": 0'), isTrue);
    });

    test('3. Boolean schema generates boolean false', () {
      final spec = {
        "openapi": "3.1.0",
        "info": {"title": "Test", "version": "1.0.0"},
        "paths": {
          "/test": {
            "post": {
              "requestBody": {
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "is_active": {"type": "boolean"},
                      },
                    },
                  },
                },
              },
            },
          },
        },
      };

      final data = OpenApiParser.parse(spec);
      final sample = data.endpoints.first.requestBody!.sampleJson;
      expect(sample.contains('"is_active": false'), isTrue);
    });

    test('4. Array schema generates array [] / [""]', () {
      final spec = {
        "openapi": "3.1.0",
        "info": {"title": "Test", "version": "1.0.0"},
        "paths": {
          "/test": {
            "post": {
              "requestBody": {
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "tags": {
                          "type": "array",
                          "items": {"type": "string"},
                        },
                        "empty_list": {"type": "array"},
                      },
                    },
                  },
                },
              },
            },
          },
        },
      };

      final data = OpenApiParser.parse(spec);
      final sample = data.endpoints.first.requestBody!.sampleJson;
      expect(sample.contains('"tags": [\n    ""\n  ]'), isTrue);
      expect(sample.contains('"empty_list": []'), isTrue);
    });

    test('5. Object schema generates object {}', () {
      final spec = {
        "openapi": "3.1.0",
        "info": {"title": "Test", "version": "1.0.0"},
        "paths": {
          "/test": {
            "post": {
              "requestBody": {
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "meta": {"type": "object"},
                      },
                    },
                  },
                },
              },
            },
          },
        },
      };

      final data = OpenApiParser.parse(spec);
      final sample = data.endpoints.first.requestBody!.sampleJson;
      expect(sample.contains('"meta": {}'), isTrue);
    });

    test('6. example/default/enum schema precedence is honored', () {
      final spec = {
        "openapi": "3.1.0",
        "info": {"title": "Test", "version": "1.0.0"},
        "paths": {
          "/test": {
            "post": {
              "requestBody": {
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "with_example": {
                          "type": "string",
                          "example": "custom_example_val",
                          "default": "default_val",
                        },
                        "with_default": {"type": "integer", "default": 42},
                        "with_enum": {
                          "type": "string",
                          "enum": ["MYSQL", "POSTGRESQL"],
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      };

      final data = OpenApiParser.parse(spec);
      final sample = data.endpoints.first.requestBody!.sampleJson;
      expect(sample.contains('"with_example": "custom_example_val"'), isTrue);
      expect(sample.contains('"with_default": 42'), isTrue);
      expect(sample.contains('"with_enum": "MYSQL"'), isTrue);
    });

    test(
      '7. \$ref-generated string and object properties resolve recursively',
      () {
        final spec = {
          "openapi": "3.1.0",
          "info": {"title": "Test", "version": "1.0.0"},
          "paths": {
            "/test": {
              "post": {
                "requestBody": {
                  "content": {
                    "application/json": {
                      "schema": {"\$ref": "#/components/schemas/NestedModel"},
                    },
                  },
                },
              },
            },
          },
          "components": {
            "schemas": {
              "NestedModel": {
                "type": "object",
                "properties": {
                  "id": {"type": "string"},
                  "child": {"\$ref": "#/components/schemas/ChildModel"},
                },
              },
              "ChildModel": {
                "type": "object",
                "properties": {
                  "label": {"type": "string", "example": "child_label"},
                },
              },
            },
          },
        };

        final data = OpenApiParser.parse(spec);
        final sample = data.endpoints.first.requestBody!.sampleJson;
        expect(sample.contains('"id": ""'), isTrue);
        expect(sample.contains('"label": "child_label"'), isTrue);
      },
    );

    testWidgets(
      '8. Altr Stream-aware model selector populates logical_model_id in request body',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Select POST /api/v1/altrql/bind
        await tester.tap(
          find.byKey(const Key('api_endpoint_POST_/api/v1/altrql/bind')),
        );
        await tester.pumpAndSettle();

        // Verify Contextual ID Helpers card
        expect(find.text('Contextual ID Helpers'), findsOneWidget);
        expect(
          find.byKey(const Key('api_body_model_selector')),
          findsOneWidget,
        );

        // Select Logical Model from dropdown
        await tester.tap(find.byKey(const Key('api_body_model_selector')));
        await tester.pumpAndSettle();
        await tester.tap(find.textContaining('ParityUsersModel').last);
        await tester.pumpAndSettle();

        // Verify request body editor is populated with model ID
        final editor = tester.widget<TextField>(
          find.byKey(const Key('api_request_body_editor')),
        );
        expect(
          editor.controller!.text.contains(
            '5b1ee481-68dd-4c4d-ba34-6c884b166b35',
          ),
          isTrue,
        );
      },
    );

    testWidgets(
      '9. Altr Stream-aware source selector populates source_id in request body',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Select POST /api/v1/altrql/bind
        await tester.tap(
          find.byKey(const Key('api_endpoint_POST_/api/v1/altrql/bind')),
        );
        await tester.pumpAndSettle();

        // Select Physical Source from dropdown
        expect(
          find.byKey(const Key('api_body_source_selector')),
          findsOneWidget,
        );
        await tester.tap(find.byKey(const Key('api_body_source_selector')));
        await tester.pumpAndSettle();
        await tester.tap(find.textContaining('Production-MongoDB').last);
        await tester.pumpAndSettle();

        // Verify request body editor is populated with source ID
        final editor = tester.widget<TextField>(
          find.byKey(const Key('api_request_body_editor')),
        );
        expect(
          editor.controller!.text.contains(
            '9f8b7a6c-5d4e-3f2a-1b0c-9d8e7f6a5b4c',
          ),
          isTrue,
        );
      },
    );

    testWidgets(
      '10. Altr Stream-aware mapping selector populates mapping_id in request body',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Select POST /api/v1/altrql/bind
        await tester.tap(
          find.byKey(const Key('api_endpoint_POST_/api/v1/altrql/bind')),
        );
        await tester.pumpAndSettle();

        // Select Mapping from dropdown
        expect(
          find.byKey(const Key('api_body_mapping_selector')),
          findsOneWidget,
        );
        await tester.tap(find.byKey(const Key('api_body_mapping_selector')));
        await tester.pumpAndSettle();
        await tester.tap(find.textContaining('Mapping 1a2b3c4d...').last);
        await tester.pumpAndSettle();

        // Verify request body editor is populated with mapping ID
        final editor = tester.widget<TextField>(
          find.byKey(const Key('api_request_body_editor')),
        );
        expect(
          editor.controller!.text.contains(
            '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
          ),
          isTrue,
        );
      },
    );

    testWidgets(
      '11. Valid AltrQL bind request execution sends valid JSON payload',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient(
          executionResultToReturn: ApiExecutionResult(
            statusCode: 200,
            statusText: '200 OK',
            duration: const Duration(milliseconds: 25),
            requestMethod: 'POST',
            requestUrl: 'http://localhost:8000/api/v1/altrql/bind',
            requestHeaders: {'Content-Type': 'application/json'},
            requestBody:
                '{"query": "SELECT * FROM users", "source_id": "9f8b7a6c-5d4e-3f2a-1b0c-9d8e7f6a5b4c"}',
            responseHeaders: {'content-type': 'application/json'},
            responseBody: {
              'success': true,
              'bound_ir': {'target': 'users'},
            },
            isSuccess: true,
          ),
        );

        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Select POST /api/v1/altrql/bind
        await tester.tap(
          find.byKey(const Key('api_endpoint_POST_/api/v1/altrql/bind')),
        );
        await tester.pumpAndSettle();

        // Populate source_id via helper
        await tester.tap(find.byKey(const Key('api_body_source_selector')));
        await tester.pumpAndSettle();
        await tester.tap(find.textContaining('Production-MongoDB').last);
        await tester.pumpAndSettle();

        // Execute request
        await tester.ensureVisible(find.byKey(const Key('api_execute_button')));
        await tester.tap(find.byKey(const Key('api_execute_button')));
        await tester.pumpAndSettle();

        expect(find.text('200 OK'), findsOneWidget);
        expect(mockClient.lastExecutedMethod, 'POST');
        expect(mockClient.lastExecutedPath, '/api/v1/altrql/bind');
        expect(mockClient.lastExecutedBody is Map, isTrue);
        expect(
          (mockClient.lastExecutedBody as Map)['source_id'],
          '9f8b7a6c-5d4e-3f2a-1b0c-9d8e7f6a5b4c',
        );
      },
    );

    testWidgets(
      '12. Invalid required identifier is clearly handled with warning message',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Select POST /api/v1/altrql/bind
        await tester.tap(
          find.byKey(const Key('api_endpoint_POST_/api/v1/altrql/bind')),
        );
        await tester.pumpAndSettle();

        // Clear the source_id in the editor
        final editor = find.byKey(const Key('api_request_body_editor'));
        await tester.enterText(
          editor,
          '{"query": "SELECT * FROM users", "source_id": ""}',
        );
        await tester.pumpAndSettle();

        // Tap Execute
        await tester.ensureVisible(find.byKey(const Key('api_execute_button')));
        await tester.tap(find.byKey(const Key('api_execute_button')));
        await tester.pumpAndSettle();

        // Verify clear SnackBar warning
        expect(
          find.text(
            'Please select or enter a valid source_id in the request body.',
          ),
          findsOneWidget,
        );
      },
    );

    testWidgets(
      '13. Align Suggestion Helper dynamically generates valid entity_mappings JSON payload',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Select POST /api/v1/registry/models/{model_id}/align/suggestions
        await tester.tap(
          find.byKey(
            const Key(
              'api_endpoint_POST_/api/v1/registry/models/{model_id}/align/suggestions',
            ),
          ),
        );
        await tester.pumpAndSettle();

        // Verify Align Suggestion Builder Card
        expect(
          find.byKey(const Key('api_align_suggestion_builder_card')),
          findsOneWidget,
        );

        // Verify dynamically populated namespace controller has discovered DB
        final nsInput = tester.widget<TextField>(
          find.byKey(const Key('api_align_namespace_input')),
        );
        expect(nsInput.controller!.text, 'altr_test_db');

        // Verify confidence controller is editable and has default value
        final confInput = tester.widget<TextField>(
          find.byKey(const Key('api_align_confidence_input')),
        );
        expect(confInput.controller!.text, '0.95');

        // Tap Apply Align Suggestion
        await tester.ensureVisible(
          find.byKey(const Key('api_apply_align_suggestion_button')),
        );
        await tester.tap(
          find.byKey(const Key('api_apply_align_suggestion_button')),
        );
        await tester.pumpAndSettle();

        // Verify editor content has valid structured payload
        final editor = tester.widget<TextField>(
          find.byKey(const Key('api_request_body_editor')),
        );
        final bodyText = editor.controller!.text;
        expect(
          bodyText.contains(
            '"source_id": "9f8b7a6c-5d4e-3f2a-1b0c-9d8e7f6a5b4c"',
          ),
          isTrue,
        );
        expect(bodyText.contains('"entity_mappings"'), isTrue);
        expect(
          bodyText.contains('"logical_entity_id": "entity-users-1"'),
          isTrue,
        );
        expect(
          bodyText.contains('"physical_entity_name": "parity_users"'),
          isTrue,
        );
        expect(
          bodyText.contains('"physical_namespace": "altr_test_db"'),
          isTrue,
        );
        expect(bodyText.contains('"confidence": 0.95'), isTrue);
        expect(bodyText.contains('"field_mappings"'), isTrue);
        expect(bodyText.contains('"logical_field_id": "field-name-1"'), isTrue);
      },
    );

    testWidgets(
      '14. Contextual Dropdowns visibly retain and display selected values',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Select POST /api/v1/altrql/bind
        await tester.tap(
          find.byKey(const Key('api_endpoint_POST_/api/v1/altrql/bind')),
        );
        await tester.pumpAndSettle();

        // Tap model selector and select
        await tester.tap(find.byKey(const Key('api_body_model_selector')));
        await tester.pumpAndSettle();
        await tester.tap(find.textContaining('ParityUsersModel').last);
        await tester.pumpAndSettle();

        // Dropdown value matches selected model ID
        final modelDropdown = tester.widget<DropdownButton<String>>(
          find.byKey(const Key('api_body_model_selector')),
        );
        expect(modelDropdown.value, '5b1ee481-68dd-4c4d-ba34-6c884b166b35');
      },
    );

    testWidgets(
      '15. Pydantic 422 validation response displays human-readable error summary and raw toggle',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient(
          executionResultToReturn: ApiExecutionResult(
            statusCode: 422,
            statusText: '422 Unprocessable Entity',
            duration: const Duration(milliseconds: 20),
            requestMethod: 'POST',
            requestUrl: 'http://localhost:8000/api/v1/altrql/bind',
            requestHeaders: {'Content-Type': 'application/json'},
            requestBody: '{"query": "SELECT * FROM users", "source_id": ""}',
            responseHeaders: {'content-type': 'application/json'},
            responseBody: {
              'detail': [
                {
                  'loc': ['body', 'entity_mappings', 0, 'physical_entity_name'],
                  'msg': 'Field required',
                  'type': 'missing',
                },
              ],
            },
            errorMessage: 'Unprocessable Entity',
            isSuccess: false,
          ),
        );

        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // Select POST /api/v1/altrql/bind
        await tester.tap(
          find.byKey(const Key('api_endpoint_POST_/api/v1/altrql/bind')),
        );
        await tester.pumpAndSettle();

        // Populate source_id via helper so request proceeds
        await tester.tap(find.byKey(const Key('api_body_source_selector')));
        await tester.pumpAndSettle();
        await tester.tap(find.textContaining('Production-MongoDB').last);
        await tester.pumpAndSettle();

        // Execute request
        await tester.ensureVisible(find.byKey(const Key('api_execute_button')));
        await tester.tap(find.byKey(const Key('api_execute_button')));
        await tester.pumpAndSettle();

        // Verify Validation Error summary card
        expect(
          find.byKey(const Key('api_validation_summary_card')),
          findsOneWidget,
        );
        expect(find.text('Request validation failed'), findsOneWidget);
        expect(find.textContaining('physical_entity_name'), findsWidgets);
        expect(find.textContaining('Entity mapping #1'), findsWidgets);
        expect(find.textContaining('This field is required.'), findsOneWidget);

        // Verify Raw Response toggle
        expect(
          find.byKey(const Key('api_toggle_raw_response_button')),
          findsOneWidget,
        );
        await tester.tap(
          find.byKey(const Key('api_toggle_raw_response_button')),
        );
        await tester.pumpAndSettle();

        expect(find.textContaining('"detail"'), findsWidgets);
      },
    );

    testWidgets(
      '16. All six modular API Explorer widgets are instantiated and verified in widget hierarchy',
      (WidgetTester tester) async {
        tester.view.physicalSize = const Size(1440, 1400);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        final mockClient = MockApiExplorerClient();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.lightTheme,
            home: Scaffold(body: ApiDocsScreen(apiClient: mockClient)),
          ),
        );
        await tester.pumpAndSettle();

        // 1. ApiConsoleHeader is present
        expect(find.byType(ApiConsoleHeader), findsOneWidget);

        // 2. ApiEndpointSidebar is present
        expect(find.byType(ApiEndpointSidebar), findsOneWidget);

        // 3. ApiEndpointDocumentation is present
        expect(find.byType(ApiEndpointDocumentation), findsOneWidget);

        // 4. ApiTryItOutPanel is present
        expect(find.byType(ApiTryItOutPanel), findsOneWidget);

        // 5. ApiParameterCard is present within Try It Out panel
        expect(find.byType(ApiParameterCard), findsOneWidget);

        // 6. ApiRequestBodyCard is present within Try It Out panel for endpoints with request body
        await tester.tap(
          find.byKey(const Key('api_endpoint_POST_/api/v1/execute')),
        );
        await tester.pumpAndSettle();
        expect(find.byType(ApiRequestBodyCard), findsOneWidget);
      },
    );
  });
}
